import { pathName } from "./server";
//左侧菜单配置
export default [
    {
        name:"检查安排",
        url:pathName+"",
        icon:"ace-icon fa fa-book",
        permission:9,
        child:[
            {
                name:"检查指标",
                url:pathName+"/checkList",
                permission:9,
                icon:"",
            },
            {
                name:"检查期次",
                url:pathName+"/checkPlan",
                permission:9,
                icon:"",
            }
        ]
    },
    {
        name:"检查工作",
        url:pathName+"",
        icon:"ace-icon glyphicon glyphicon-check",
        permission:1,
        child:[
            {
                name:"检查小组",
                url:pathName+"/checkGroup",
                permission:5,
                icon:"",
            },
            {
                name:"检查工作",
                url:pathName+"/checkWork",
                permission:5,
                icon:"",
            },
            {
                name:"我的检查工作",
                url:pathName+"/myCheck",
                permission:1,
                icon:"",
            },
            {
                name:"问题反馈",
                url:pathName+"/feedback",
                permission:1,
                icon:"",
            }
        ]
    },
    {
        name:"统计总结",
        url:pathName+"",
        icon:"ace-icon fa fa-bar-chart-o",
        permission:7,
        child:[
            {
                name:"安全责任人登录表",
                url:pathName+"",
                permission:7,
                icon:"",
            },
            {
                name:"检查统计表",
                url:pathName+"",
                permission:7,
                icon:"",
            },
            {
                name:"评奖评优",
                url:pathName+"",
                permission:7,
                icon:"",
            }
        ]
    },
    {
        name:"基础数据管理",
        url:pathName+"",
        icon:"ace-icon fa fa-cog",
        permission:5,
        child:[
            {
                name:"实验室单位管理",
                url:pathName+"/orgList",
                permission:5,
                icon:'',
            },
            {
                name:"人员管理",
                url:pathName+"/userList",
                permission:5,
                icon:'',
            },
            {
                name:"房间及分组管理",
                url:pathName+"/zone",
                permission:5,
                icon:'',
            }
        ]
    },
    {
        name:"系统基础数据设置",
        url:pathName+"",
        icon:"ace-icon fa fa-cog",
        permission:5,
        child:[
            {
                name:"菜单栏设置",
                url:pathName+"/menu",
                permission:5,
                icon:'',
            },
            {
                name:"角色设置",
                url:pathName+"/role",
                permission:5,
                icon:'',
            },
            {
                name:"权限点设置",
                url:pathName+"/permission",
                permission:5,
                icon:'',
            }
        ]
    }
]