//左侧菜单配置
export default [
    {
        name:"检查安排",
        url:"",
        icon:"0",
        route:"/",
        child:[
            {
                name:"检查指标",
                url:"",
                parent:"/",
                route:"/",
                icon:"",
            },
            {
                name:"检查期次",
                url:"",
                parent:"/",
                route:"",
                icon:"",
            }
        ]
    },
    {
        name:"检查工作",
        url:"",
        icon:"",
        route:"",
        child:[
            {
                name:"检查小组",
                url:"",
                parent:"1",
                route:"",
                icon:"",
            },
            {
                name:"检查工作",
                url:"",
                parent:"1",
                route:"",
                icon:"",
            },
            {
                name:"问题反馈",
                url:"",
                parent:"1",
                route:"",
                icon:"",
            }
        ]
    },
    {
        name:"统计总结",
        url:"",
        route:"",
        icon:"",
        child:[
            {
                name:"安全责任人登录表",
                url:"",
                parent:"2",
                route:"",
                icon:"",
            },
            {
                name:"检查统计表",
                url:"",
                parent:"2",
                route:"",
                icon:"",
            },
            {
                name:"评奖评优",
                url:"",
                parent:"2",
                route:"",
                icon:"",
            }
        ]
    },
    {
        name:"退出系统",
        url:"",
        parent:"3",
        route:"",
        icon:""
    }
]